[package]
name = "KernelBase"
version = "0.1.0"
authors = ["SparkyPotato"]
edition = "2018"

[[bin]]
name = "KernelBase"
path = "Source/Main.rs"

[dependencies]
bootloader = "0.9.*"
lazy_static = { version = "1.*", features = [ "spin_no_std" ] }
spin = "0.5.2"
volatile = "0.2.6" 
