[package]
name = "bootloader"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
paging = { path = "../paging", features = ["init"] }

elf = { version = "0.7.2", default-features = false }
uefi = "0.24.0"
